### ISSUE TITLE
Fatal error on activation

### ISSUE THREAD

**Issue by dmccan** [woocommerce/wc-smooth-generator#138]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

On a new local install added Woo and this plugin via zip download.  On activation a fatal error was triggered.  It appears the code is looking ofr a directory that is missing from the install.  

[10-Jul-2024 03:01:48 UTC] PHP Warning:  require(/Users/david/Sites/woo/wp-content/plugins/wc-smooth-generator-trunk/vendor/autoload.php): Failed to open stream: No such file or directory in /Users/david/Sites/woo/wp-content/plugins/wc-smooth-generator-trunk/wc-smooth-generator.php on line 23
[10-Jul-2024 03:01:48 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/Users/david/Sites/woo/wp-content/plugins/wc-smooth-generator-trunk/vendor/autoload.php' (include_path='.:/Applications/MAMP/bin/php/php8.1.13/lib/php') in /Users/david/Sites/woo/wp-content/plugins/wc-smooth-generator-trunk/wc-smooth-generator.php:23
Stack trace:
#0 /Users/david/Sites/woo/wp-admin/includes/plugin.php(2389): include_once()
#1 /Users/david/Sites/woo/wp-admin/includes/plugin.php(675): plugin_sandbox_scrape('wc-smooth-gener...')
#2 /Users/david/Sites/woo/wp-admin/plugins.php(60): activate_plugin('wc-smooth-gener...', 'https://woo.loc...', false)
#3 {main}
  thrown in /Users/david/Sites/woo/wp-content/plugins/wc-smooth-generator-trunk/wc-smooth-generator.php on line 23

### WordPress Environment

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.0.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.54 (Unix) mod_fastcgi/mod_fastcgi-SNAP-0910052141 OpenSSL/1.0.2u mod_wsgi/3.5 Python/2.7.18
PHP Version: 8.1.13
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 5.7.39
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1
page: 7
post: 2
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooPayments: by Automattic – 7.8.1
WooCommerce: by Automattic – 9.0.2

### Inactive Plugins (2) ###

WooCommerce Shipping & Tax: by WooCommerce – 2.6.1
WooCommerce Smooth Generator: by Automattic – 1.1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 2 KB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /Users/david/Sites/woo/wp-content/plugins/woocommerce/templates/block-notices/error.php
/Users/david/Sites/woo/wp-content/plugins/woocommerce/templates/block-notices/notice.php
/Users/david/Sites/woo/wp-content/plugins/woocommerce/templates/block-notices/success.php


### WooPayments ###

Version: 7.8.1
Connected to WPCOM: ❌ No
Logging: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
pattern-toolkit-full-composability
product-pre-publish-modal
settings
async-product-editor-category-field
launch-your-store
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-11 02:55:27 -05:00
Options: ✔
Notes: 58
Onboarding: completed

### Action Scheduler ###

Complete: 3
Oldest: 2024-07-09 21:56:33 -0500
Newest: 2024-07-09 21:59:47 -0500

Pending: 1
Oldest: 2024-07-10 21:56:33 -0500
Newest: 2024-07-10 21:56:33 -0500


### Status report information ###

Generated at: 2024-07-09 22:24:12 -05:00
```
</details>

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce and WooCommerce Smooth Generator plugins are active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by coreymckrill** [comment]
Hi @dmccan when you downloaded the zip file, did you get the [1.1.0 release zip](https://github.com/woocommerce/wc-smooth-generator/releases/tag/1.1.0), or did you just generate the zip file from the main page of this repository? If the latter, you're probably missing the build step, which would explain the errors.

**Comment by dmccan** [comment]
Yes, that was it.  Thank you.
